- name: Create wireguard container
  community.docker.docker_container:
    name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    pull: true
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.src_valid_mark: "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    state: started
    env:
      PASSWORD: "{{ WG_PASSWORD }}"
      WG_HOST: "{{ WG_SERVER_IP_ADDRESS }}"
    ports:
      - "{{ WG_WEB_UDP_PORT }}:51821/udp"
      - "{{ WG_WEB_TCP_PORT }}:51821/tcp"
    volumes:
      - /{{ USERNAME }}/{{ DATA_DIR }}/wireguard/config:/etc/wireguard
    restart_policy: unless-stopped
